name: Deploy Vite Application

on:
  push:
    branches:
      - main # Set to your default branch, e.g., main or master
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Prebuild
        run: |
          sed -i "s|// base: '/ChordTrainer'|base: '/ChordTrainer'|" vite.config.js

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Set this to your build output directory
